language: python
sudo: required
dist: xenial
python:
  - "3.7"
env:
  - FLASK=1.0.2

install:
  - pip install -q Flask==$FLASK
  - pip install -r requirements.txt
  
script:
  - py.test
  - cd scripts
  - python reset_database.py test
