SET FOREIGN_KEY_CHECKS=0;

-- UBER_CLINICS 
DROP TABLE IF EXISTS UBER_CLINICS;
CREATE TABLE UBER_CLINICS (
  id int(11) NOT NULL AUTO_INCREMENT,
  physical_address varchar(100) DEFAULT NULL,
  name varchar(100) DEFAULT NULL,
  start_time datetime DEFAULT '2019-01-01 08:00:00', 
  end_time datetime DEFAULT '2019-01-07 20:00:00',
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- USERS
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  id int(11) NOT NULL AUTO_INCREMENT,
  first_name varchar(100) NOT NULL,
  last_name varchar(100) NOT NULL,
  password varchar(100) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- PATIENTS
DROP TABLE IF EXISTS PATIENTS;
CREATE TABLE PATIENTS (
  id int(11) NOT NULL AUTO_INCREMENT,
  user_fk int(11) NOT NULL,
  email varchar(100) NOT NULL,
  health_card varchar(14) NOT NULL,
  phone_number varchar(15) NOT NULL,
  birthday date NOT NULL,
  gender varchar(15) NOT NULL,
  physical_address varchar(100) NOT NULL,
  date_of_last_annual varchar(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY PATIENTS_USERS_FK (user_fk),
  CONSTRAINT PATIENTS_USERS_FK FOREIGN KEY (user_fk) REFERENCES USERS (id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- NURSES
DROP TABLE IF EXISTS NURSES;
CREATE TABLE NURSES (
  id int(11) NOT NULL AUTO_INCREMENT,
  user_fk int(11) NOT NULL,
  access_id varchar(8) NOT NULL,
  PRIMARY KEY (id),
  KEY NURSES_USERS_FK (user_fk),
  CONSTRAINT NURSES_USERS_FK FOREIGN KEY (user_fk) REFERENCES USERS (id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- DOCTORS
DROP TABLE IF EXISTS DOCTORS;
CREATE TABLE DOCTORS (
  id int(11) NOT NULL AUTO_INCREMENT,
  user_fk int(11) NOT NULL,
  permit_number int(7) NOT NULL,
  specialty varchar(100) NOT NULL,
  city varchar(100) NOT NULL,
  PRIMARY KEY (id),
  KEY DOCTORS_USERS_FK (user_fk),
  CONSTRAINT DOCTORS_USERS_FK FOREIGN KEY (user_fk) REFERENCES USERS (id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- DOCTOR CLINIC ASSIGNMENTS
DROP TABLE IF EXISTS DOCTOR_CLINIC_ASSIGNMENT;
CREATE TABLE DOCTOR_CLINIC_ASSIGNMENT (
  id int(11) NOT NULL AUTO_INCREMENT,
  clinic_id int(11) DEFAULT NULL,
  doctor_id int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (doctor_id) REFERENCES DOCTORS (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (clinic_id) REFERENCES CLINICS (id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- ROOMS
DROP TABLE IF EXISTS ROOMS;
CREATE TABLE ROOMS (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(100) DEFAULT NULL,
  clinic_id int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY CLINIC_FK (clinic_id),
  CONSTRAINT CLINIC_FK FOREIGN KEY (clinic_id) REFERENCES UBER_CLINICS (id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- ROOM_BOOKINGS
DROP TABLE IF EXISTS ROOM_BOOKINGS;
CREATE TABLE ROOM_BOOKINGS (
  id int(11) NOT NULL AUTO_INCREMENT,
  room_id int(11) NOT NULL,
  date_time datetime NOT NULL,
  walk_in tinyint(1) NOT NULL,
  PRIMARY KEY (id),
  KEY ROOM_FK (room_id),
  CONSTRAINT ROOM_FK FOREIGN KEY (room_id) REFERENCES ROOMS (id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- DOCTOR_GENERIC_AVAILABILITIES
DROP TABLE IF EXISTS DOCTOR_GENERIC_AVAILABILITIES;
CREATE TABLE DOCTOR_GENERIC_AVAILABILITIES (
  id int(11) NOT NULL AUTO_INCREMENT,
  doctor_id int(11) NOT NULL,
  date_time datetime NOT NULL,
  walk_in tinyint(1) NOT NULL,
  PRIMARY KEY (id),
  KEY DOCTOR_FK (doctor_id),
  CONSTRAINT DOCTOR_FK FOREIGN KEY (doctor_id) REFERENCES DOCTORS (id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- DOCTOR_ADJUSTMENTS
DROP TABLE IF EXISTS DOCTOR_ADJUSTMENTS;
CREATE TABLE DOCTOR_ADJUSTMENTS (
  id int(11) NOT NULL AUTO_INCREMENT,
  doctor_id int(11) NOT NULL,
  date_time datetime NOT NULL,
  operation_type_add tinyint(1) NOT NULL,
  walk_in tinyint(1) NOT NULL,
  PRIMARY KEY (id),
  KEY DOCTOR_ID_FK (doctor_id),
  CONSTRAINT DOCTOR_ID_FK FOREIGN KEY (doctor_id) REFERENCES DOCTORS (id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

-- APPOINTMENTS
DROP TABLE IF EXISTS APPOINTMENTS;
CREATE TABLE APPOINTMENTS (
  id int(11) NOT NULL AUTO_INCREMENT,
  clinic_id int(11) NOT NULL,
  room_id int(11) NOT NULL,
  doctor_id int(11) NOT NULL,
  patient_id int(11) NOT NULL,
  date_time datetime NOT NULL,
  walk_in tinyint(1) NOT NULL,
  PRIMARY KEY (id),
  KEY CLINICS_ID_FK (clinic_id),
  KEY ROOMS_ID_FK (room_id),
  KEY DOCTORS_ID_FK (doctor_id),
  KEY PATIENTS_ID_FK (patient_id),
  CONSTRAINT CLINICS_ID_FK FOREIGN KEY (clinic_id) REFERENCES UBER_CLINICS (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT ROOMS_ID_FK FOREIGN KEY (room_id) REFERENCES ROOMS (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT DOCTORS_ID_FK FOREIGN KEY (doctor_id) REFERENCES DOCTORS (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT PATIENTS_ID_FK FOREIGN KEY (patient_id) REFERENCES PATIENTS (id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS=1;